// ============================================================
// Problem: Divide-by-2 Clock Divider
// ============================================================
// Design a simple clock divider that generates an output clock with
// half the frequency of the input clock.
//
// Module interface:
// module clk_div2 (
//   input  logic clk,
//   input  logic rst_n,
//   output logic clk_div2
// );
//
// Requirements:
// 1. The module should generate clk_div2 from the input clk.
//
// 2. Reset behavior:
//    - rst_n is an active-low asynchronous reset.
//    - When rst_n is low, clk_div2 should reset to 0.
//
// 3. Divide-by-2 behavior:
//    - On every rising edge of clk, clk_div2 should toggle its value.
//    - If clk_div2 was 0, it becomes 1.
//    - If clk_div2 was 1, it becomes 0.
//
// 4. Frequency behavior:
//    - Since clk_div2 toggles once per input clock cycle, it takes two
//      input clock cycles to complete one full output period.
//    - Therefore, the output frequency is half of the input frequency.
//
// 5. Duty cycle:
//    - After reset is released, clk_div2 should stay high for one clk cycle
//      and low for one clk cycle.
//    - This produces an approximately 50% duty-cycle divided clock.
//
// 6. Output type:
//    - clk_div2 should be a registered output.
//    - It should only change on the rising edge of clk or during reset.
//
// 7. Implementation style:
//    - Use SystemVerilog.
//    - Use always_ff for sequential logic.
//    - Use nonblocking assignment.
//    - Do not use delays or simulation-only constructs.
//    - The design should be synthesizable.
//
// 8. Assumptions:
//    - clk is a free-running clock.
//    - rst_n is asynchronous active-low reset.
//    - The divided clock is generated by a flip-flop toggle.
// ============================================================

`default_nettype none

module clk_div2 (
  input  logic clk,
  input  logic rst_n,
  output logic clk_div2
);
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            clk_div2 <= 0;
        end else begin
            clk_div2 <= ~clk_div2;
        end
    end
endmodule