// ============================================================
// Problem: ALU Control Decoder
// ============================================================
// Design a combinational ALU control decoder for a simple RISC-V-like
// processor datapath.
//
// The module receives a high-level ALU operation code from the main
// control unit, along with instruction function fields, and generates
// the final ALU control signal used by the ALU.
//
// Module interface:
// module alu_control (
//   input  logic [1:0] alu_op,
//   input  logic [2:0] funct3,
//   input  logic       funct7_b5,
//   output logic [3:0] alu_ctrl
// );
//
// Requirements:
// 1. The module should be purely combinational.
//    - alu_ctrl should update whenever alu_op, funct3, or funct7_b5 changes.
//    - Do not use clk or reset.
//    - Use always_comb.
//
// 2. alu_op determines the broad instruction category:
//
//    alu_op = 2'b00:
//      - Used for load/store address calculation.
//      - ALU operation should be ADD.
//      - alu_ctrl = 4'd0.
//
//    alu_op = 2'b01:
//      - Used for branch comparison.
//      - ALU operation should be SUB.
//      - alu_ctrl = 4'd1.
//
//    alu_op = 2'b10:
//      - Used for R-type or ALU-type instructions.
//      - Decode the exact operation using funct3 and funct7_b5.
//
//    default:
//      - alu_ctrl should default to ADD.
//      - alu_ctrl = 4'd0.
//
// 3. For alu_op = 2'b10, decode funct3 as follows:
//
//    funct3 = 3'b000:
//      - If funct7_b5 = 0, select ADD.
//      - If funct7_b5 = 1, select SUB.
//
//    funct3 = 3'b001:
//      - Select SLL, logical left shift.
//
//    funct3 = 3'b010:
//      - Select SLT, signed less-than comparison.
//
//    funct3 = 3'b100:
//      - Select XOR.
//
//    funct3 = 3'b101:
//      - If funct7_b5 = 0, select SRL, logical right shift.
//      - If funct7_b5 = 1, select SRA, arithmetic right shift.
//
//    funct3 = 3'b110:
//      - Select OR.
//
//    funct3 = 3'b111:
//      - Select AND.
//
//    default:
//      - Select ADD.
//
// 4. ALU control encoding:
//
//      alu_ctrl = 4'd0  -> ADD
//      alu_ctrl = 4'd1  -> SUB
//      alu_ctrl = 4'd2  -> AND
//      alu_ctrl = 4'd3  -> OR
//      alu_ctrl = 4'd4  -> XOR
//      alu_ctrl = 4'd5  -> SLT
//      alu_ctrl = 4'd6  -> SLL
//      alu_ctrl = 4'd7  -> SRL
//      alu_ctrl = 4'd8  -> SRA
//
// 5. The output alu_ctrl should be compatible with the ALU module that
//    uses the same operation encoding.
//
// 6. Implementation style:
//    - Use SystemVerilog.
//    - Use always_comb.
//    - Use a case statement on alu_op.
//    - Use a nested case statement on funct3 when alu_op = 2'b10.
//    - Provide default cases to avoid latches.
//    - The design should be synthesizable.
//
// 7. Assumptions:
//    - funct7_b5 is the bit that distinguishes ADD vs SUB and SRL vs SRA.
//    - alu_op is generated by a separate main control unit.
//    - This module only decodes ALU operation selection; it does not
//      perform the ALU operation itself.
// ============================================================

`default_nettype none

module alu_control (
  input  logic [1:0] alu_op,
  input  logic [2:0] funct3,
  input  logic       funct7_b5,
  output logic [3:0] alu_ctrl
);
  always_comb begin
    case (alu_op)
      2'b00: alu_ctrl = 4'd0;  // Load/Store — ADD
      2'b01: alu_ctrl = 4'd1;  // Branch    — SUB
      2'b10: begin
        case (funct3)
          3'b000: alu_ctrl = funct7_b5 ? 4'd1 : 4'd0;  // SUB / ADD
          3'b001: alu_ctrl = 4'd6;                      // SLL
          3'b010: alu_ctrl = 4'd5;                      // SLT
          3'b100: alu_ctrl = 4'd4;                      // XOR
          3'b101: alu_ctrl = funct7_b5 ? 4'd8 : 4'd7;  // SRA / SRL
          3'b110: alu_ctrl = 4'd3;                      // OR
          3'b111: alu_ctrl = 4'd2;                      // AND
          default: alu_ctrl = 4'd0;
        endcase
      end
      default: alu_ctrl = 4'd0;
    endcase
  end
endmodule